// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/garcia-paulo/upvotes-grpc/application/servicers"
	"github.com/garcia-paulo/upvotes-grpc/infra/config"
	"github.com/garcia-paulo/upvotes-grpc/infra/database"
	"github.com/garcia-paulo/upvotes-grpc/infra/repositories"
	"github.com/garcia-paulo/upvotes-grpc/presentation"
	"github.com/garcia-paulo/upvotes-grpc/presentation/servers"
)

// Injectors from wire.go:

func InitializeServer() *presentation.Server {
	configConfig := config.NewConfig()
	databaseDatabase := database.NewDatabase(configConfig)
	userRepository := repositories.NewUserRepository(databaseDatabase)
	userServicer := servicers.NewUserServicer(userRepository)
	userServer := servers.NewUserServer(userServicer)
	postRepository := repositories.NewPostRepository(databaseDatabase)
	postServicer := servicers.NewPostServicer(postRepository)
	postServer := servers.NewPostServer(postServicer)
	server := presentation.NewServer(userServer, configConfig, postServer)
	return server
}
