// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/upvotes-grpc/garcia-paulo/infra/config"
	"github.com/upvotes-grpc/garcia-paulo/infra/database"
	"github.com/upvotes-grpc/garcia-paulo/infra/repositories"
	"github.com/upvotes-grpc/garcia-paulo/presentation"
	"github.com/upvotes-grpc/garcia-paulo/presentation/servers"
)

// Injectors from wire.go:

func InitializeServer() *presentation.Server {
	configConfig := config.NewConfig()
	databaseDatabase := database.NewDatabase(configConfig)
	userRepository := repositories.NewUserRepository(databaseDatabase)
	userServer := servers.NewUserServer(userRepository)
	server := presentation.NewServer(userServer, configConfig)
	return server
}
